Add an action to build the docker image for building ParallelZone
NWChemEx-Project/ParallelZone pull request #105
Opened 2023-04-17 23:06 UTC by yzhang-23

Adding an action to build a docker image for building ParallelZone.

**PR Type**

- [ ] Breaking change
- [ ] Feature
- [ ] Patch
- [X] CI

**Brief Description**

**Not In Scope**

**PR Checklist**

- [ ] Documentation (comments, API, user, design, and developer as applicable)
    - [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
    - [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
    - [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
    - [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [ ] Testing (unit, integration, performance, as applicable)
    - [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
    - [Integration](https://nwchemex-project.github.io/.github/testing/integration.html)
    - [Performance](https://nwchemex-project.github.io/.github/testing/performance.html)
- [ ] Code adheres to organization standards
    - [C++](https://nwchemex-project.github.io/.github/coding/cxx/cxx_conventions.html)
    - [Python](https://nwchemex-project.github.io/.github/coding/python/python_conventions.html)
    - [Doxygen Conventions](https://nwchemex-project.github.io/.github/documenting/doxygen_conventions.html)
    - [reST Conventions](https://nwchemex-project.github.io/.github/documenting/rst_conventions.html)

**TODOs**

- [X] Write the .yaml file.
- [X] Test in my forked branch of ParallelZone.

2023-04-17 23:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NWChemEx-Project/ParallelZone?pullRequest=105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/NWChemEx-Project/ParallelZone?pullRequest=105) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yzhang-23<br/>:x: license[bot]<br/><hr/>**license[bot]** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NWChemEx-Project/ParallelZone?pullRequest=105) it.</sub>

2023-04-18 01:39 UTC, ryanmrichard requested changes

2023-04-18 01:39 UTC, ryanmrichard commented on Docker/ParallelZone.Dockerfile
I was thinking there would be a image in the .github repo, then we'd use the existing CI infrastructure here to build ParallelZone, except it would start from the base image in the .github repo, not the default image GitHub uses for actions (I think that's how actions work)

2023-04-18 01:39 UTC, ryanmrichard commented on .github/workflows/docker_image_build.yaml
I don't think we want to build ParallelZone into an image at this point. We want to test PZ on an image. When we make PZ into an image we want to do so without the tests, with optimizations enabled, and in the minimal size possible.

2023-04-18 02:12 UTC, yzhang-23 commented on Docker/ParallelZone.Dockerfile
So, you mean for each repo, we pull a basic image first, add additional packages into it if necessary, and then build the repo?

2023-04-18 02:16 UTC, yzhang-23 commented on .github/workflows/docker_image_build.yaml
I did not build ParallelZone into an image. The dockerfile here is for building an environment to build ParallelZone. I have confirmed that ParallelZone can be built with this image. I also don't think we need to build this image every time when we check in some codes, so I set the "on" condition of this image building action as the dockerfile has been changed.

2023-04-18 14:50 UTC, ryanmrichard commented on .github/workflows/docker_image_build.yaml
I edited NWChemEx-Project/.github#81, and added #107 and #109 to hopefully clarify the workflow I see happening. I'm hoping that this PR can be made to address #107 and its current contents moved to the .github repo to address NWChemEx-Project/.github#81.

2023-04-18 19:15 UTC, ryanmrichard commented
@yzhang-23 I also meant to point out that the `Breaking change`, `Feature`, and `Patch` check boxes on the top are meant to correspond to semantic versioning. The idea is we know what label to put on the PR (bump:major, bump:minor, bump:patch, respectively) based on which box is checked. In theory I'd like to automate the labeling somehow, but haven't figured out how.

2023-04-19 16:55 UTC, ryanmrichard commented
As mentioned, building the base image for ParallelZone (which also be the base image for several other repos) should happen in .github (see https://github.com/NWChemEx-Project/.github/issues/81). So I'm going to close this PR (note this does not delete the branch, so the files are still available).

2023-04-19 16:55 UTC, closed without merging